### ISSUE TITLE
GDASApp EE2 compliance checklist for GFS v17 & v18

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#1254]
This issue is opened as a one-stop-shop to list GDASApp related EE2 compliance issues
- [ ] Build issues; Do not build libraries e.g. CRTM, FMS, FV3, MOM6, Icepak, etc.  
   - [ ] Use the ufs-weather-model library in GDASApp in place of FV3
   - [ ] Use the ufs-weather-model library in GDASApp in place of MOM6 and Icepak
   - [ ] Use CRTM and CRTM-fix module instead of building and downloading fix files - GDASApp issue [#1268](https://github.com/NOAA-EMC/GDASApp/issues/1268).
   - [ ] Don’t download test data as part of build process - GDASApp issue [#1269](https://github.com/NOAA-EMC/GDASApp/issues/1269)
   - [x] Use FMS module - GDASApp PR [#1221](https://github.com/NOAA-EMC/GDASApp/pull/1221)
- [ ] Install executables into `$HOMEgfs/exec` - GDASApp issue [#1302](https://github.com/NOAA-EMC/GDASApp/issues/1302)
- [ ] Build warnings and build and run in debug mode
- [x] Relocate job scripts to global-workflow
   - [x]  partially addressed by g-w PR [#2920](https://github.com/NOAA-EMC/global-workflow/pull/2920)
- [ ] Copy any other needed files to global-workflow as part of link_workflow.sh (no job script should look in the gdas.cd directory)

Separate issues and PRs will be opened to address the above tasks.

**Comment by RussTreadon-NOAA** [comment]
GDASApp PR #1221 resolved the FMS task.

**Comment by RussTreadon-NOAA** [comment]
CRTMv3 should address task _Use CRTM and CRTM-fix module instead of building and downloading fix files_.

**Comment by RussTreadon-NOAA** [comment]
GDASApp issue #1268 has been created to track the move from using a GDASapp built CRTM to using a pre-installed CRTM build via a module load.

**Comment by RussTreadon-NOAA** [comment]
GDASApp issue [#1269](https://github.com/NOAA-EMC/GDASApp/issues/1269) has been created to track the addition of flags to optionally turn off the downloading of test data during the GDASApp build.

**Comment by CoryMartin-NOAA** [comment]
I see in this PR: https://github.com/JCSDA-internal/ioda-converters/pull/1548

```
  set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
  set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_RPATH}:${CMAKE_BINARY_DIR}/lib64")
```

I wonder if we can add this to our `gdas.x` compile and solve the copy vs link executable issue?

**Comment by RussTreadon-NOAA** [comment]
Thanks @CoryMartin-NOAA for spotting https://github.com/JCSDA-internal/ioda-converters/pull/1548.  Trying this in GDASApp is a good idea.  Worse case is that it doesn't solve the copy -vs- link executable issue.  Best case is that it does and we can check this item off the GDASApp EE2 compliance list.

**Comment by RussTreadon-NOAA** [comment]
GDASApp PR #1282 along with g-w PR [#2920](https://github.com/NOAA-EMC/global-workflow/pull/2920) partially address checklist item _Relocate job scripts to global-workflow_.  Work for these PRs is complete.

**Comment by RussTreadon-NOAA** [comment]
Superseded by issues with [EE2 label](https://github.com/NOAA-EMC/GDASApp/issues?q=is%3Aissue%20state%3Aopen%20label%3AEE2).  

Close this issue.
